# Site settings
baseurl: "" 
url: ""

# API settings
google_api_key:

# Build settings

# Markdown (gituhub only uses kramdown)
markdown: kramdown

# Set pagination
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
